### PR TITLE
Split project into modules (statsd, newrelic, prometheus, datadog)

### LINKED ISSUE #2: remove "io.d11" % "zhttp" from dependencies
This project (at the moment) unnecessarily pulls in zhttp.
For using in my project that is not using zhttp but just the prometheus part I had to do 

```scala
libraryDependencies += "dev.zio" %% "zio-metrics-connectors" % "2.0.0" exclude("io.d11", "zhttp_2.13"),
```

### LINKED ISSUE #3: create submodules for newrelic, prometheus, statsd
At the moment, the part for newrelic pulls in zio-json. For projects that do not need newrelic this is undesirable. It would be good if the integrations would be split into different submodules and the dependencies properly adjusted (so that e.g. zio-json is only pulled in when using the newrelic connector)

I suggest: 

- zio-metric-connectors-core
- zio-metric-connectors-newrelic
- zio-metric-connectors-statsd
- zio-metric-connectors-prometheus

as module names.

### PR DESCRIPTION
**Pull request by calvinlfer**
* Update libraries (ZIO HTTP & ZIO JSON)
* Update Scala 3 version
* Update SBT

Closes https://github.com/zio/zio-metrics-connectors/issues/2
Closes https://github.com/zio/zio-metrics-connectors/issues/3

### CODE REVIEW

**Comment by petoalbert** [comment]
Nice changes @calvinlfer! Thank you! I can merge this once you fixed the merge conflicts. 

Would you like to update the documentation in this PR too? I am thinking that we should mention [here](https://zio.dev/zio-metrics-connectors/metrics/prometheus-client) the additional artifacts have to be specified in the dependencies.

**Comment by calvinlfer** [comment]
> Nice changes @calvinlfer! Thank you! I can merge this once you fixed the merge conflicts.
> 
> Would you like to update the documentation in this PR too? I am thinking that we should mention [here](https://zio.dev/zio-metrics-connectors/metrics/prometheus-client) the additional artifacts have to be specified in the dependencies.

Hey @petoalbert, afaik you don't need to include any additional dependencies for prometheus, its fully self-contained since we build the strings within the library. It's on the user to expose the strings for scraping via a web endpoint. Is that the documentation you are after?

**Comment by calvinlfer** [comment]
I've pulled all examples into the sample project module

**Comment by petoalbert** [comment]
@calvinlfer I meant that the [documentation for the prometheus client](https://zio.dev/zio-metrics-connectors/metrics/prometheus-client/) should mention that the first step to use the module should be to specify `dev.zio:zio-metrics-connectors-prometheus` as a dependency, and the same for every other metric client. Currently the only artefact mentioned in the documentation is [here](https://zio.dev/zio-metrics-connectors/getting-started#installation).

**Review by petoalbert — APPROVED** [review]

**Comment by petoalbert** [comment]
I am happy to merge this now and create an issue to track the documentation. 🙂

**Comment by petoalbert** [comment]
@calvinlfer https://github.com/zio/zio-metrics-connectors/issues/47

**Pull request merged**
