### PR TITLE
Add min / max metrics from Summary and Histogram to Prometheus connector

### PR DESCRIPTION
**Pull request by vladimirkl**
This PR does the following:
1.  Adds missing min / max metrics from Summary and Histogram to Prometheus connector. 
2. Fixes double space after bucket label - this rendering is  not standard and breaks some scrapers. 
3. Adds basic test suite for PrometheusEncoder

### CODE REVIEW

**Review by guizmaii — APPROVED** [review]

**Comment by vladimirkl** [comment]
@atooni Could you review this PR? Seems that approve from @guizmaii is not enough to unblock merging

**Comment by guizmaii** [comment]
> Seems that approve from @guizmaii is not enough to unblock merging

Yeah, my approval has no real value here. I just read the code and it seems ok to me, but I don't know the code of this project

**Review by atooni — APPROVED** [review]

**Comment by atooni** [comment]
Approved - thanks for the enhancement !

**Comment by vladimirkl** [comment]
@atooni fixed  test compilation under Scala 2.12 - please approve again to run the workflow

**Comment by vladimirkl** [comment]
@atooni All checks are green, can you merge it?

**Pull request merged**
